# INFRASTRUCTURE NAME
name: "spring-boot-dev"

# SERVICE NETWORKS
networks:
  spring-boot-api-network:
    driver: bridge

# SERVICES
services:
  db:
    image: postgres:18-alpine
    container_name: helpdesk-db
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - spring-boot-api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile

    image: tebohogiven/spring-boot-app:0.0.1

    ports:
      - "8080:8080"

    volumes:
      # Mounts container uploads to a local folder named 'uploads' in your project root
      - upload_data:/opt/app/uploads

    environment:
      SPRING_APPLICATION_NAME: helpdesk

      # Datasource
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${PG_USER}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_SQL_INIT_MODE: always

      # Flyway Configuration
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"

      # JPA
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_OPEN_IN_VIEW: false
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      APP_DATASOURCE_TYPE: postgresql

      # JWT
      APP_JWT_SECRET: ${JWT_SECRET_KEY}
      APP_JWT_ACCESS_TOKEN_EXPIRY_MS: ${JWT_VALIDITY}
      APP_JWT_REFRESH_TOKEN_EXPIRY_MS: ${JWT_REFRESH_VALIDITY}

      # File Upload
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 100MB
      APP_UPLOAD_STORAGE_PATH: /opt/app/uploads

      # Swagger / SpringDoc
      SPRINGDOC_API_DOCS_PATH: /v3/api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_SWAGGER_UI_OPERATIONSSORTER: method
      SPRINGDOC_API_DOCS_ENABLED: true
      SPRINGDOC_SWAGGER_UI_ENABLED: true

      # Account Lockout
      APP_SECURITY_MAX_LOGIN_ATTEMPTS: 5

      # Mail
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true

      # RabbitMQ
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      SPRING_RABBITMQ_TECHNICIAN_ASSIGNMENT_QUEUE: ${TECHNICIAN_ASSIGNMENT_QUEUE}
      SPRING_RABBITMQ_TICKET_STATUS_CHANGE_QUEUE: ${TICKET_STATUS_CHANGE_QUEUE}
      SPRING_RABBITMQ_TICKET_COMMENT_QUEUE: ${TICKET_COMMENT_QUEUE}
      SPRING_RABBITMQ_TICKET_CREATION_QUEUE: ${TICKET_CREATION_QUEUE}

      SPRING_RABBITMQ_TECHNICIAN_ASSIGNMENT_EXCHANGE: ${TECHNICIAN_ASSIGNMENT_EXCHANGE}
      SPRING_RABBITMQ_TICKET_STATUS_CHANGE_EXCHANGE: ${TICKET_STATUS_CHANGE_EXCHANGE}
      SPRING_RABBITMQ_TICKET_COMMENT_EXCHANGE: ${TICKET_COMMENT_EXCHANGE}
      SPRING_RABBITMQ_TICKET_CREATION_EXCHANGE: ${TICKET_CREATION_EXCHANGE}

      SPRING_RABBITMQ_TECHNICIAN_ASSIGNED_ROUTING_KEY: ${TECHNICIAN_ASSIGNED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKET_STATUS_CHANGED_ROUTING_KEY: ${TICKET_STATUS_CHANGED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKET_COMMENT_ADDED_ROUTING_KEY: ${TICKET_COMMENT_ADDED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKET_CREATED_ROUTING_KEY: ${TICKET_CREATED_ROUTING_KEY}

    restart: always

    networks:
      - spring-boot-api-network

    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_ERLANG_COOKIE: "secret_cookie_string"

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - spring-boot-api-network

    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 7
      start_period: 10s

volumes:
  postgres_data:
  upload_data: