# INFRASTRUCTURE NAME
name: "spring-boot-dev"

# SERVICE NETWORKS
networks:
  spring-boot-api-network:
    driver: bridge

# SERVICES
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: tebohogiven/spring-boot-app:0.0.1
    environment:
      SPRING_APPLICATION_NAME: springjwtauth
      SPRING_DATASOURCE_URL: jdbc:${{GovHelpDesk_db.DATABASE_URL}}
#      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      SPRING_JPA_OPEN_IN_VIEW: false
      JWT_SECRETKEY: ${JWT_SECRET_KEY}
      JWT_VALIDITY: ${JWT_VALIDITY}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SPRING_RABBITMQ_TECHNICIANASSIGNMENTQUEUE: ${TECHNICIAN_ASSIGNMENT_QUEUE}
      SPRING_RABBITMQ_TICKETSTATUSCHANGEQUEUE: ${TICKET_STATUS_CHANGE_QUEUE}
      SPRING_RABBITMQ_TICKETCOMMENTQUEUE: ${TICKET_COMMENT_QUEUE}
      SPRING_RABBITMQ_TICKETCREATIONQUEUE: ${TICKET_CREATION_QUEUE}
      SPRING_RABBITMQ_TECHNICIANASSIGNMENTEXCHANGE: ${TECHNICIAN_ASSIGNMENT_EXCHANGE}
      SPRING_RABBITMQ_TICKETSTATUSCHANGEEXCHANGE: ${TICKET_STATUS_CHANGE_EXCHANGE}
      SPRING_RABBITMQ_TICKETCOMMENTEXCHANGE: ${TICKET_COMMENT_EXCHANGE}
      SPRING_RABBITMQ_TICKETCREATIONEXCHANGE: ${TICKET_CREATION_EXCHANGE}
      SPRING_RABBITMQ_TECHNICIANASSIGNEDROUTINGKEY: ${TECHNICIAN_ASSIGNED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKETSTATUSCHANGEDROUTINGKEY: ${TICKET_STATUS_CHANGED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKETCOMMENTADDEDROUTINGKEY: ${TICKET_COMMENT_ADDED_ROUTING_KEY}
      SPRING_RABBITMQ_TICKETCREATEDROUTINGKEY: ${TICKET_CREATED_ROUTING_KEY}
    restart: always
    networks:
      - spring-boot-api-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring-boot-api-network
    healthcheck: # ✅ Check if RabbitMQ is ready
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
